// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXE9P9GKS09dEwZdtlGOiG3q7FJqJrL2Q',
    appId: '1:719358747427:web:ab2b1b806f8645a332a296',
    messagingSenderId: '719358747427',
    projectId: 'activity12-bd3b2',
    authDomain: 'activity12-bd3b2.firebaseapp.com',
    storageBucket: 'activity12-bd3b2.firebasestorage.app',
    measurementId: 'G-NSNDVF1R30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJ6WAjEWJ35f313_RWbn9II-rVHqfshM',
    appId: '1:719358747427:android:5e3ece392e34188c32a296',
    messagingSenderId: '719358747427',
    projectId: 'activity12-bd3b2',
    storageBucket: 'activity12-bd3b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fW1X_ePUPlt87gggBcaphL5KKl9aLV0',
    appId: '1:719358747427:ios:610bf8e4a1e154b132a296',
    messagingSenderId: '719358747427',
    projectId: 'activity12-bd3b2',
    storageBucket: 'activity12-bd3b2.firebasestorage.app',
    iosBundleId: 'com.example.activity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7fW1X_ePUPlt87gggBcaphL5KKl9aLV0',
    appId: '1:719358747427:ios:610bf8e4a1e154b132a296',
    messagingSenderId: '719358747427',
    projectId: 'activity12-bd3b2',
    storageBucket: 'activity12-bd3b2.firebasestorage.app',
    iosBundleId: 'com.example.activity12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXE9P9GKS09dEwZdtlGOiG3q7FJqJrL2Q',
    appId: '1:719358747427:web:b2d4723b27ba178c32a296',
    messagingSenderId: '719358747427',
    projectId: 'activity12-bd3b2',
    authDomain: 'activity12-bd3b2.firebaseapp.com',
    storageBucket: 'activity12-bd3b2.firebasestorage.app',
    measurementId: 'G-XXSSTBVGK3',
  );
}
